version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: relatorio_financeiro:latest
    container_name: relatorio_financeiro
    ports:
      - "8052:8052"
    volumes:
      - shared_data:/relatorio_financeiro/shared_data
    env_file:
      - .env
    restart: always

  request_job:
    build:
      context: .
      dockerfile: Dockerfile
    image: relatorio_financeiro_request:latest
    container_name: relatorio_financeiro_request
    command: >
      sh -c "while true; do python request.py && sleep 43200; done"
    volumes:
      - shared_data:/relatorio_financeiro/shared_data
    depends_on:
      - app
    env_file:
      - .env
    restart: always

volumes:
  shared_data:
