services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: relatorio_financeiro:latest
    container_name: relatorio_financeiro
    ports:
      - "8052:8052"
    volumes:
      - shared_data:/relatorio_financeiro/shared_data
      - ./cache.db:/relatorio_financeiro/cache.db
    env_file:
      - .env
    environment:
      - ORACLE_INSTANT_CLIENT_PATH=/usr/lib/oracle/instantclient
    restart: unless-stopped

  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    image: vw_financeiro_obra:latest
    container_name: vw_financeiro_obra_scheduler
    command: python scheduler.py        # seu loop de refresh em 2 h
    depends_on:
      - app
    volumes:
      - ./cache.db:/app/cache.db
      - ./shared_data:/app/shared_data
    env_file:
      - .env
    environment:
      - ORACLE_INSTANT_CLIENT_PATH=/usr/lib/oracle/instantclient
    restart: unless-stopped

volumes:
  shared_data:
