services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: relatorio_financeiro:latest
    container_name: relatorio_financeiro
    ports:
      - "8052:8052"
    volumes:
      - shared_data:/relatorio_financeiro/shared_data
    env_file:
      - .env
    environment:
      - ORACLE_INSTANT_CLIENT_PATH=/usr/lib/oracle/instantclient
    restart: unless-stopped

  request_job:
    build:
      context: .
      dockerfile: Dockerfile
    image: relatorio_financeiro:latest
    container_name: relatorio_financeiro_request
    command: >
      sh -c "while true; do python request.py && sleep 43200; done"
    volumes:
      - shared_data:/relatorio_financeiro/shared_data
    env_file:
      - .env
    environment:
      - ORACLE_INSTANT_CLIENT_PATH=/usr/lib/oracle/instantclient
    depends_on:
      - app
    restart: unless-stopped

volumes:
  shared_data:
