version: "3.9"

services:
  app:
    build: .
    container_name: relatorio_financeiro
    ports:
      - "8052:8052"
    volumes:
      - shared_data:/shared_data
    environment:
      - FLASK_SECRET
      - LDAP_SERVER
      - LDAP_BIND_DN
      - LDAP_BIND_PASSWORD
      - LDAP_BASE_DN
      - LDAP_USER_SEARCH_FILTER


  request_job:
    build: .
    container_name: relatorio_financeiro_request
    command: >
      sh -c "while true; do python /VW_FINANCEIRO_OBRA/request.py && sleep 43200; done"
    volumes:
      - shared_data:/shared_data
    depends_on:
      - app                                     # opcional

volumes:
  shared_data:
